server:
  port: 0

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/yandex-praktikum/java-explore-with-me-config
          search-paths: configs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90